version: '3'
services:
  # ip_proxy_pool:
  #   image: zonghi/ip-proxy-pool:latest
  #   container_name: IPProxyPool     
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./Dockerfiles/IPProxyPool/config.py:/IPProxyPool/config.py
  #     - ./wait-for-it.sh:/wait-for-it.sh
  #   entrypoint: "/wait-for-it.sh -t 0 mysql:3306 -- "
  #   command: python3 IPProxy.py

  compose_pool:
    image: zonghi/ip-proxy-pool:latest
    container_name: compose_pool     
    ports:
      - 8123:8123
    volumes:
      - ./Dockerfiles/compose_pool/IPProxyPool:/compose_pool
      # - ./wait-for-it.sh:/wait-for-it.sh
    # entrypoint: "/wait-for-it.sh -t 0 mysql:3306 -- "
    command: python3 IPProxy.py

  mysql:
    restart: always
    image: mysql:latest
    container_name: mysql
    # volumes:
    #   - ./Dockerfiles/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=proxy"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306
  redis:
    image: redis
    command: redis-server --requirepass ""
  go-ip-pool:
    depends_on:
      - redis
    image: go-ip-pool:latest
    command: go run ./cmd -S=all -C=/conf/conf.yaml
    volumes:
      - ./Dockerfiles/go_ip_pool/conf:/conf
    ports:
      - 8090:8090
  proxypool:
    image: zonghi/proxypool:latest
    command: ./proxypool
    volumes:
      - ./Dockerfiles/proxypool/conf/app.ini:/proxypool/conf/app.ini
      - ./wait-for-it.sh:/wait-for-it.sh
    entrypoint: "/wait-for-it.sh -t 0 mysql:3306 -- "
    ports:
      - 8080:8080
  proxy_pool:
    image: jhao104/proxy_pool:latest
    container_name: proxy_pool
    ports:
      - "5010:5010"
    links:
      - redis
    environment:
      DB_CONN: "redis://@redis:6379/0"
  # qt_stable_filter_server:
  #   image: zonghi/hikyuu:latest
  #   container_name: hikyuu
  #   command: bash /root/code/docker/hikyuu/cron/loop.sh
