version: '2'
services:
  proxy_pool:
    image: jhao104/proxy_pool:latest
    container_name: proxy_pool
    ports:
      - "5010:5010"
    links:
      - proxy_redis
    environment:
      DB_CONN: "redis://@proxy_redis:6379/0"

  ip_proxy_pool:
    build: ./Dockerfiles/IPProxyPool
    container_name: IPProxyPool
    # ports:
    #   - "5010:5010"
    # links:
    #   - proxy_redis
    # environment:
    #   DB_CONN: "redis://@proxy_redis:6379/0"

  proxy_redis:
    image: "redis"
    container_name: proxy_redis